apiVersion: v1
kind: Service
metadata:
  name: availability-service
spec:
  selector:
    app: availability-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
