apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: availability-service
  template:
    metadata:
      labels:
        app: availability-service
    spec:
      containers:
      - name: availability-service
        image: availability_service:latest
        ports:
        - containerPort: 5000
