apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-service
  template:
    metadata:
      labels:
        app: flight-service
    spec:
      containers:
      - name: flight-service
        image: flight_service:latest
        ports:
        - containerPort: 5000
